### ISSUE TITLE
Add good Mark down Documentation

### ISSUE THREAD

**Issue by Bashamega** [Bashamega/calculator#1]
Hello:)

We need some volunteers to fill in and write the empty documentation files for the tools.

Each file will consist of 3 section:
1. About: A short description of the function.
2. Usage: How to link it to the project and some test cases.
3. Contributors: A table of the username and the GitHub link of the contributor (Until now it is only me).

Requirements:
1. A good understanding of the importance of Documentation.
2. Some Experience with Readme

**Comment by Bashamega** [comment]
> It looks like everything else is done except for a Contributor list. Is that correct?

No, the contributor list would be a good idea but it is not the priority. The priority is create documentations on how to use the functions, currently i have created only the files

**Comment by martincarapia** [comment]
[This](https://github.com/Bashamega/calculator?tab=readme-ov-file#usage) Looks like it's showing how to use the functions to me.

**Comment by Bashamega** [comment]
> [This](https://github.com/Bashamega/calculator?tab=readme-ov-file#usage) Looks like it's showing how to use the functions to me.

I mean like for each function an md file which have like and about it and an example and the contributers that contributed on the function
